# server:
#  port: 8080

spring:
  profiles:
    active: dev # 指定环境名
---
# 开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8081
---
# 生产环境
spring:
  config:
    activate:
      on-profile: pro
server:
  # port: 80 # localhost/...