version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: 'no'
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=12345678
      - "TZ=Asia/Shanghai"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'