version: "3.8"

services:
  cache:
    image: redis:latest
    container_name: redis-docker
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456